name: Run gulp tasks

permissions:
  actions: write
  #checks: read|write|none
  #contents: read|write|none
  #deployments: read|write|none
  #id-token: read|write|none
  #issues: read|write|none
  #discussions: read|write|none
  #packages: read|write|none
  #pages: read|write|none
  #pull-requests: read|write|none
  #repository-projects: read|write|none
  #security-events: read|write|none
  #statuses: read|write|none

# Controls when the action will run.
on:
  push:
    # On which branch
    branches: ["main"]
    # On which files
    # paths: ["scripts/scripts.js", "styles/styles.scss"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 12.22.2
      - run: npm ci
      - run: gulp dist

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git status
          git add dist
          git commit -m "Update gulp output files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # force: true
